# Generated by Django 2.2.5 on 2019-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_clik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clik',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
