# Generated by Django 2.2.6 on 2019-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_clik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Clik',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stock',
        ),
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
