# Generated by Django 2.2.6 on 2019-10-05 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20191005_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='codeProduit',
            field=models.CharField(default='rr', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='articles',
            field=models.ManyToManyField(to='djangoapp.Article'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.CharField(default='rrr', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='modePaiement',
            field=models.CharField(default='CASH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='pointsFidelite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
