# Generated by Django 2.2.6 on 2019-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_auto_20191005_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=20)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='articles',
            field=models.ManyToManyField(to='djangoapp.ArticlesList'),
        ),
    ]
