# Generated by Django 2.2.6 on 2019-10-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20191010_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='articles',
        ),
    ]
