# Generated by Django 2.2.6 on 2019-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_remove_ticket_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='articles',
            field=models.ManyToManyField(to='djangoapp.ArticlesList'),
        ),
    ]
