# Generated by Django 2.2.6 on 2019-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_ticket_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslist',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleslist',
            name='promo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
