# Generated by Django 2.2.6 on 2019-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20191028_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transmis',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
