# Generated by Django 2.2.6 on 2019-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_ticket_transmis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='codeProduit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articleslist',
            name='codeProduit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.CharField(max_length=50),
        ),
    ]
