# Generated by Django 2.2.7 on 2019-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20191122_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleslist',
            old_name='prix',
            new_name='prixAvant',
        ),
        migrations.AddField(
            model_name='articleslist',
            name='prixApres',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
