# Generated by Django 2.2.7 on 2019-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_auto_20191213_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
